Initial dev commit
vladl2802/3d-renderer pull request #1
Opened 2024-01-11 09:38 UTC by vladl2802

2024-01-12 15:45 UTC, DimaTrushin requested changes
В целом неплохо. Я накидал каких-то общих и частных замечаний. Обрати внимание, что если я где-то указывал на ошибку, то я в похожих местах не повторялся больше, я ожидаю, что ты по аналогии найдешь все такие места и поправишь их.

Еще обрати внимание на Primitive и мои комментарии. Я думаю, что нужно либо полиморфизм перенести на уровень объектов, а не примитивов. Но в любом случае я думаю, что надо делать стирающие типы, а не то, что у тебя. Ну и фейл с new, это просто пиздец.

И еще обрати внимание на рендерер. У него не дложно быть шаблонных параметров ширина и высота. Я расписал подробно как и что надо исправить.

2024-01-12 15:45 UTC, DimaTrushin commented on .gitignore
> +build
Пустая строка в начале каждого файла. Иначе пользователи гита будут видеть сообщения об этой ошибке.

2024-01-12 15:45 UTC, DimaTrushin commented on CMakeLists.txt
> +add_link_options(-fsanitize=address)
Никогда не пиши компиляторо специфические флаги. Если ты ожидаешь такие флаги, то делай их только для того компилятора, для которого они работают. Поставь тут if для gcc (или это для clang?). Либо можно поставить заглушку, которая проверяет, что компилятор gcc и иначе валится с сообщением об ошибке.

2024-01-12 15:45 UTC, DimaTrushin commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 23)
Этого мало, надо еще
```cpp
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```
Иначе эта строка ничего не значит.
И еще, какими фичами 23 плюсов ты пользуешься? Это реально нельзя собрать на меньшей версии?

2024-01-12 15:45 UTC, DimaTrushin commented on CMakeLists.txt
> +include_directories(/usr/local/include/eigen3)
Очень плохая идея писать машино зависимые пути для библиотек. Я например не смогу собрать на своей машине это приложение не изменяя этот путь. Лучше подключить eigen как git submodule и использовать путь относительно папок проекта. Посмотри тут https://git-scm.com/book/en/v2/Git-Tools-Submodules как это надо делать.

2024-01-12 15:45 UTC, DimaTrushin commented on src/geometry.h
> +#include </usr/local/include/eigen3/Eigen/Core>
У тебя в include_directories уже прописан пусть /usr/local/include/engen3. Потому ты можешь писать смело 
```cpp
#include "Eigen/Core"
```
Кроме того, так как написано сейчас -- это машино зависимо. Я не смогу например собрать этот проект у себя, пока не перепишу все адреса всех инклудов у тебя. Это плохо.

2024-01-12 15:45 UTC, DimaTrushin commented on src/geometry.h
> +using Matrix = Eigen::Matrix<double, Rows, Cols>;
У Eigen Matrix шаблон использует типы int для Rows и Cols. Плохая идея делать другие типы тут в своем шаблоне. Это черевато.

2024-01-12 15:45 UTC, DimaTrushin commented on src/geometry.h
> +using RGBColor = Point;  // Move this to appropriate place
Вот это удивительно. Не уверен, что это правильно.

2024-01-12 15:45 UTC, DimaTrushin commented on src/main.cpp
> +}
Кирпичи

2024-01-12 15:45 UTC, DimaTrushin commented on src/primitive.h
> +}  // namespace primitive
Это для полиморфизма предполагалось?

2024-01-12 15:45 UTC, DimaTrushin commented on src/primitive.h
> +    Primitive(Primitive&&) = default;
сделай noexcept

2024-01-12 15:45 UTC, DimaTrushin commented on src/primitive.h
> +    Primitive& operator=(Primitive&&) = default;
сделай noexcept

2024-01-12 15:45 UTC, DimaTrushin commented on src/primitive.h
> +    std::vector<Point> get_vertices() const;
Это нормально, что ты by value возварщаешь вектор? Это потенциально дорогая операция.

2024-01-12 15:45 UTC, DimaTrushin commented on src/primitive.h
> +    Primitive(std::unique_ptr<primitive::Base>&& data);
Не уверен, что это хороший способ. Это подразумевает, что кто-то снаружи будет возиться с деталями имплементации твоего класса Primitive и сам будет его кишки инициализировать. Лучше закрой этот конструктор и сделай статические методы, которые будут возвращать построенный Primitive. Должно работать по типу так
```cpp
class Primitive {
  static Primitive createPoint();
  static Primitive createTriangle();
}
```
и что-то в этом духе. Тогда не надло будет пользователю возиться с наследованем.

2024-01-12 15:45 UTC, DimaTrushin commented on src/primitive.h
> +    std::unique_ptr<primitive::Base> data_;
1) В целом это не самая лучшая идея использовать полиморфизм для хранения данных. Потому что это тот случай, когда при обработке важно, чтобы данные лежали близко. И подобный подход будет сильно бить про производительности. Опять же, можно посмотреть как это будет работать.
2) Я бы предпочел использовать стирающие типы. Ты по сути сейчас пишешь свой стирающий тип. А значит тебе нужно лишь сделать шаблонный конструктор вида
```cpp
template<class T>
class Model : public Base {
public:
  Model(const T& data) : data_(data) {}
  Model(T&& data) : data_(std::move(data)) {}
private:
  T data_;
};

template<class T>
Primitive(T&& primitive) : data_(std::make_unique<Model<T>>(std::forward<T>(primitive))) {}
```
Посмотри у меня в Library репозитории файл AnyMovable.

2024-01-12 15:45 UTC, DimaTrushin commented on src/primitive.h
> +    Base& operator=(Base&&) = default;
Вот это все можно не указывать, когда все остальное по дефолту.

2024-01-12 15:45 UTC, DimaTrushin commented on src/primitive.h
> +    PrimitiveType type_;
Никогда не храни в интерфейсе данные. Раздели это на два этажа.

2024-01-12 15:45 UTC, DimaTrushin commented on src/primitive.h
> +class Point : public Base {
Вместо такого наследования лучше сделай стирающий тип. Это сильно упростит работу твоего кода. Ты сможешь убрать связь между твоими примитивами и интерфейсом полностью.

2024-01-12 15:45 UTC, DimaTrushin commented on src/primitive.h
> +    virtual std::vector<renderer::Point> get_vertices() const = 0;
Мне не нравится, что ты возвращаешь by value. Это потенциально дорого.

2024-01-12 15:45 UTC, DimaTrushin commented on src/primitive.h
> +    virtual Primitive transform(const Matrix<4, 4>& operation) const override;
Сдесь слово virtual лишнее, достаточно override.

2024-01-12 15:45 UTC, DimaTrushin commented on src/primitive.h
> +    Point(std::array<renderer::Point, 1> vertices, RGBColor color);
Я не понимаю, почему ты принимаешь тут std::array вместо vertices, учитывая, что у тебя array имеет длину 1!

2024-01-12 15:45 UTC, DimaTrushin commented on src/primitive.h
> +    std::array<renderer::Point, 1> vertices_;
Нахуя, а главное зачем? Почему не Point vertex_?

2024-01-12 15:45 UTC, DimaTrushin commented on src/primitive.h
> +    virtual std::vector<renderer::Point> get_vertices() const = 0;
Я думаю правильный интерфейс другой. Надо вернуть прокси объект, у которого есть методы begin и end, чтобы проитерироваться по всем вершинам. И уже каждый класс создает свою имплементацию этого прокси объекта. Ну и конечно же это все лекго через стирающие типы сделать. Потому что по сути тебе нужен view на произвольный контейнер. А это класс, который имеет методы begin и end. И еще надо сделать два вида методов. const и non const, чтобы можно было еще и менять объекты (мало ли).

2024-01-12 15:45 UTC, DimaTrushin commented on src/primitive.h
> +// I will remove inheritance here when finish baseline
Посмотри выше мое предложение про стирающие типы.

2024-01-12 15:45 UTC, DimaTrushin commented on src/primitive.h
> +    virtual Base* clone() const = 0;
Лучше, чтобы clone возвращал сразу unique_ptr<Base> ибо тогда он будет владеющим. Это не испортит и не изменит ничего в использовании, но сделает код более надежным.

2024-01-12 15:45 UTC, DimaTrushin commented on src/primitive.cpp
> +    data_.reset(other.data_->clone());
Это не работает для само присваивания. Надо сделать так
```cpp
  return *this = Primitive(other);
```
Это использует copy constructor + move assignment.

2024-01-12 15:45 UTC, DimaTrushin commented on src/primitive.cpp
> +    : data_(std::unique_ptr<primitive::Base>(other.data_->clone())) {
Это плохо. У тебя эта имплементация упадет, когда в other.data_ неинициализировано, будет обращение по nullptr. Тут надо
```cpp
(other.data_ ? other.data_->clone() : nullptr)
```
Ты явно не слушал мой курс по плюсам и не смотрел записи. Я на последней лекции про это подробно рассказывал.

2024-01-12 15:45 UTC, DimaTrushin commented on src/primitive.cpp
> +        std::make_unique<primitive::Point>(perform_transform<1>(vertices_, operation), color_));
Ну вот и вскрылось где у тебя проблемы. А если бы у тебя был конструктор, который я сказал, то тут бы было бы написано
```cpp
return perform_transform<1>(vertices_, operation), color_);
```
и все.

2024-01-12 15:45 UTC, DimaTrushin commented on src/primitive.cpp
> +    return new Point(*this);
Пиздец. Никогда, НИКОГДА, НИ ПРИ КАКИХ УСЛОВИЯХ ТАК НЕ ДЕЛАЙ!!!! Это пиздец. Я просто в ахуе от этого. Никогда не испльзуй new вне конструктора.
Нет, я просто в ахуе. На сколько все красиво и аккуратно в остальном коде, на столько это полное говно тут в этой одной строчке.

2024-01-12 15:45 UTC, DimaTrushin commented on src/geometry/sphere.h
> +    const Point& get_center() const;
Если уж ты считаешь, что Point  это легкая структура и ты ее готов принимать в конструктор by value, то и возвращай ее by value.

2024-01-12 15:45 UTC, DimaTrushin commented on src/geometry/sphere.h
> +public:
Рекомендую в начале каждого класса написать
```cpp
using Point = GlobalTypes::Point;
```
А все глобальные типы внутри geometry.h завернуть в GlobalTypes namespace. Тогда у тебя будет и глобальная настройка типов и локально в каждом классе можно будет корректировать эти типы при необходимости.

2024-01-12 15:45 UTC, DimaTrushin commented on src/geometry/sphere.cpp
> +    assert(radius >= 0);
Лучше, чтобы radius > 0. Во-первых, ты скорее всего где-нибудь поделишь на него и забудешь, что ты разрешил нулевой радиус. Во-вторых, сравнение на = для double плохая тема. Всегда старайся писать строгие неравенства на double.

2024-01-12 15:45 UTC, DimaTrushin commented on src/geometry/plane.h
> +    Plane transform(const Matrix<4, 4>& operation) const;
Мне не очень нравится логика. Обычно есть два метода Inplace и out-of-place. Я предпочитаю делать так, что методы члены действуют inplace, потому что они могут быть эффективными, а вот static методы возвращают новый объект. Я к тому, что у тебя наверное все равно понадобится делать изменения inplace. Может быть стоит сделать два метода?

2024-01-12 15:45 UTC, DimaTrushin commented on src/geometry/plane.cpp
> +    normal_.normalize();
А тут не нужна проверка, что normal не нулевая?

2024-01-12 15:45 UTC, DimaTrushin commented on src/geometry/algo.h
> +namespace algo {
Есть два способа объединять алгоритмы:
1) врамках namespace
2) в рамках struct или class в виде статических методов

Я предпочитаю второй способ, потому что тогда подобные объединения можно передавать как параметры шаблона. Тут смотри по ситуации, просто совет.

2024-01-12 15:45 UTC, DimaTrushin commented on src/geometry/algo.cpp
> +    // Maybe make RandomGenerator singleton?
Мысль правильная, но можно сильно улучшить этот подход.
1) Надо завернуть весь рандом в один класс, который тебе нужен
```cpp
class Random {
public:
  // интерфейс, который ты хочешь
private:
  std::random_device rd;
  std::mt19937 rnd = rd();
};
```
2) Можно сделать этот рандом статической переменной метода и использовать ее тут.
```cpp
static Random rand;
const auto x = points[rnd.uniform(0, point.size())];
```
3) Можно завернуть этот алгоритм в class и внутри класса сделать переменную Random и вызывать ее тут.

2024-01-12 15:45 UTC, DimaTrushin commented on src/geometry/algo.cpp
> +    const auto x = points[rnd() % points.size()];
Вот это плохая тема. Ты делаешь неравномерное распределение. Если rnd() генерирует значения не в интервале кратном points.size(), то у тебя будет сильный перекос в распределении. Можешь потестить и удивиться. Лучше использовать специальные генераторы uniform_distribution и прочие.

2024-01-12 15:45 UTC, DimaTrushin commented on src/geometry/algo.cpp
> +                                     });
Выглядит так, что это можно обернуть в отдельный метод хелпер.

2024-01-12 15:45 UTC, DimaTrushin commented on src/geometry/algo.cpp
> +    Sphere res((y + z) / 2, (y - z).norm() / 2);
Я понимаю, что в алгоритмах читаемость не самое важное. Но тут из каких соображений выбирается сфера? Это типо максимальный радиус или что?

2024-01-12 15:45 UTC, DimaTrushin commented on src/geometry/algo.cpp
> +            double new_radius = (dir.norm() + res.get_radius()) / 2;
Сделай у всех констант 1. чтобы подчеркнуть, что это double. Это очень важно, особенно, когда ты прибегаешь к парадигме auto. Указывай тип в константах всегда.

2024-01-12 15:45 UTC, DimaTrushin commented on src/geometry.h
> +
Я уже написал в одном из классов про это. Надо глобальные типы завернуть внутрь отдельного namespace вроде GlobalTypes и потом из него подтягивать внутрь каждого класса через using-ги эти типы. Это позволяет глобально менять все типы и в то же время декаплит тебя от глобальных зависимостей, ты их можешь в любой точке поправить.

2024-01-12 15:45 UTC, DimaTrushin commented on src/object.h
> +    std::vector<Primitive> primitives_;
Если у тебя Object содержит целый вектор из Primitive, то плохая идея делать примитивы полиморфными. Это ломает локальность. Лучше полиморфизм сделать на уровне Object. Либо можно внутри Object хранить вектора на все виды примитивов, потому что object сам знает какие примитивы ему нужны, а какие нет. И тогда можно все виды примитивов обьрабатывать отдельно.

2024-01-12 15:45 UTC, DimaTrushin commented on src/object.h
> +
Зачем тут пробел? Выглядит так, что ты хочешь Object и ObjectWithBoundingShpere. Но лучше так не делать.

2024-01-12 15:45 UTC, DimaTrushin commented on src/object.cpp
> +      primitives_(primitives),
Глядя на то, как ты передал вектор by value я решил угадать, ты забыл тут std::move или нет. Оказалось, что забыл. А я все таки надеялся, что нет. =)

2024-01-12 15:45 UTC, DimaTrushin commented on src/object.cpp
> +Object::Object(Point position, std::vector<Primitive> primitives)
Почему это не обернуто в 
namespace renderer {
...
}
?? Выглядит так, что это не должно компилиться.

2024-01-12 15:45 UTC, DimaTrushin commented on src/object.cpp
> +using renderer::Primitive;
Лучше эти юзинги запихнуть внутрь класса Object, а тут их делать из Object:: и более того, внутри renderer namespace, а не в global.

2024-01-12 15:45 UTC, DimaTrushin commented on src/object.cpp
> +    for (auto prim : primitives) {
почему не const auto&, просто такой вызов делает копию  prim из primitives. Это может быть дорого, потому что потенциально у тебя Primitive "стирающий тип" (сейчас еще нет, но вообще может содержать много данных и тут будут дорогие копии).

2024-01-12 15:45 UTC, DimaTrushin commented on src/object.cpp
> +// Most likely will return repetitions
Что это значит?

2024-01-12 15:45 UTC, DimaTrushin commented on src/object.cpp
> +    if (std::abs(dist) <= bounding_.get_radius()) {
делай только строгие сравнения с double

2024-01-12 15:45 UTC, DimaTrushin commented on src/renderer.h
> +    float height;
Почему ты от double перешел к float внезапно?

2024-01-12 15:45 UTC, DimaTrushin commented on src/renderer.h
> +    Matrix<3, 3> direction;
Если ты хочешь инвариант, что эта матрица ортогональна, то надо делать класс. И еще плохое название, лучше orientation.

2024-01-12 15:45 UTC, DimaTrushin commented on src/renderer.h
> +struct Camera {
Я правильно понимаю, что фокусная точка у тебя всегда в центре и на фиксированном расстоянии от камеры?

2024-01-12 15:45 UTC, DimaTrushin commented on src/renderer.h
> +using Screen = std::array<std::array<RGBColor, Width>, Height>;
Это плохая тема, лучше такие сущности выделять в отдельный класс, потому что тебе рано или поздно понадобятся другие методы в нем. А еще другая проблема у тебя размеры будут вида size_t, а ты можешь ипользовать какой-то другой тип, который не является беззнаковым. И могут возникнуть проблемы со сравнением знаковых и беззнаковых типов.

2024-01-12 15:45 UTC, DimaTrushin commented on src/renderer.h
> +class Renderer {
1) Схуя ли у тебя Renderer имеет шаблонные параметры высота и ширина!? Это вообще иррелевантные параметры в run-time для экрана, а рендереру должно быть плевать на это, он вообще не должен об этом заботиться. Еще и вынесено в его compile-time интерфейс. Это ошибка дизайна.
2) У тебя вот в чем косяк. У тебя есть два экрана. Один двумерный с double координатами, а другой растровый с пикселями и вот он имеет height и width. И вот это должны быть параметры растрового экрана. И рендерер будет просто возвращать этот экран. А сколько там пикселей мы на этом уровне знать не должны. Особенно в compile-time.

2024-01-12 15:45 UTC, DimaTrushin commented on src/renderer.h
> +    Screen<Height, Width> screen;
1) Наименование приватных переменных. screen_ будет лучше. Дело в том, что переменные класса для методов класса являются глобальными. Потому лучше их имена как-то обозначать, чтобы отличать.
2) Зачем тебе хранить экран тут? Я думаю, что лучше renderer сделать без этой информации. И просто в операторе () возвращать его by value. Потому что ты скорее всего будешь эти данные потом куда-то складывать вне рендерера и куда-нибудь передавать.

2024-01-12 15:45 UTC, DimaTrushin commented on src/renderer.h
> +    const Screen<Height, Width>& operator()(const World& world, const Camera& camera);
Не уверен, что оператор это хорошая мысль. Может быть лучше функцию с нормальным названием? Но это не принципиально.

2024-01-12 15:45 UTC, DimaTrushin commented on src/renderer.h
> +}
Это называется Renderer() = default;
И не понятно зачем он нужен, если у тебя нет другого конструктора.

2024-01-12 15:45 UTC, DimaTrushin commented on src/renderer.h
> +           "Aspect ratios of camera and screen must be equal");
С чего вдруг? Камера может вполне себе растягивать или сужать картинки. В любом случае непонятно как добиться этой синхронности. Потому что у тебя по сути есть длина и ширина в пикселях и длина и ширина в double для окна камеры. Но так выглядит, что одно должно просто уметь пересчитываться в другое. То есть у тебя должны быть методы по пересчету одних координат в другие вперед и назад. И все. И никаких ошибок в run-time.

2024-01-12 15:45 UTC, DimaTrushin commented on src/renderer.h
> +    // Need to check camera direction matrix (that it's contains normalized right vector triple)\
it contains

2024-01-12 15:45 UTC, DimaTrushin commented on src/renderer.h
> +        }
Вот этот комментарий подсказывает, что ты можешь завернуть вызовы stl функций в функции класса с более благозвучными названиями. То есть тут ты можешь написать
```cpp
if (can_skip(...)) 
  continue;
```
Аналогично с другими вызовами stl методов. Дело в том, что эти методы -- это имплементация того, что ты хочешь сделать. А то что ты хочешь сделать можно оформить в виде глаголов в названиях хороших функций.

2024-01-12 15:45 UTC, DimaTrushin commented on src/renderer.h
> +        plane = plane.transform(transform_matrix);
Ну вот как я и говорил, тебе реально нужен inplace метод.

2024-01-21 09:41 UTC, vladl2802 commented on src/geometry/plane.cpp
> +    normal_.normalize();
На самом деле она не очень нужна, т.к. в этом случае Eigen говорит, что не будет менять вектор.

2024-01-21 09:47 UTC, vladl2802 commented on src/object.h
> +
Отделил, потому что думал о том, чтобы в будущем сделать несколько видов bounding'ов. Но я не уверен нужно ли это вообще.

2024-01-21 09:55 UTC, vladl2802 commented on src/renderer.h
> +struct Camera {
Вообще да, но это вроде влияет только на матрицы преобразований, поэтому я это отложил до момента, когда у меня остальная часть заработает.

2024-01-21 10:33 UTC, vladl2802 commented on src/renderer.h
> +    Screen<Height, Width> screen;
2. Хочется не пересоздавать экран каждый раз при вызове. Я понимаю, что иногда при вызове рендерера я захочу скопировать экран, но вроде это не всегда так, иногда достаточно просто ссылки.
А вообще, глобально хочется хранить два экрана. Тогда пока ссылка на один используется чтобы отрисовать его, на другой уже можно рендерить. И менять местами эти два экрана внутри. Однако я не уверен, чьей обязанностью должна быть поддержка этого инвариант. (Кажется, что рендерера)

2024-01-21 10:40 UTC, vladl2802 commented on src/object.cpp
> +// Most likely will return repetitions
Что я не убираю повторения среди вершин. Например я могу создать куб по 8 точкам, но в результате вызова get_vertices() я получу 36 точек, среди которых уникальных будет на самом деле только 8. 
Я просто не уверен, стоит ли вообще с этим что-то делать.

2024-01-21 10:49 UTC, vladl2802 commented on src/geometry/algo.cpp
> +    Sphere res((y + z) / 2, (y - z).norm() / 2);
Выбирается минимальная сфера, покрывающая точки Y и Z. А вторым проходом эта сфера расширяется до каждой точки, которая в нее не попала.

2024-01-21 10:52 UTC, vladl2802 commented on src/primitive.cpp
> +    return new Point(*this);
В свое оправдание хочу сказать, что мне показалось нелогичным возвращать unique_ptr из этой функции, потому что Primitive сам являлся оберткой над unique_ptr. Поэтому я прибегнул к таким методам)

2024-01-21 10:58 UTC, vladl2802 commented on src/primitive.h
> +    std::array<renderer::Point, 1> vertices_;
Нормальной причины нет. 
Потому что изначально у меня все преобразования были написаны так, что передавать array было проще.

2024-01-21 11:01 UTC, vladl2802 commented on src/primitive.h
> +    virtual std::vector<renderer::Point> get_vertices() const = 0;
Я понимаю, что мне здесь нужен view по сути. Но я не понимаю как мне их склеивать нормально. Поэтому я пока что решил копировать в вектор и потом их склеивать.
Вообще, я планировал переписать это на view, когда буду хранить все точки внутри одного контейнера.

2024-01-21 11:05 UTC, vladl2802 commented on src/primitive.h
> +    virtual std::vector<renderer::Point> get_vertices() const = 0;
У меня тут смысл как раз в том, что я создаю вектор, в который копирую все вершины примитива, и его возвращаю. По ссылке возвращать нельзя точно, потому что у меня тогда вектор умрет.

2024-01-21 11:15 UTC, vladl2802 commented on src/geometry.h
> +using RGBColor = Point;  // Move this to appropriate place
А что именно? Цвет или Transform?
С цветами мне понадобиться работать как с векторами чуть позже, когда я буду добавлять градиенты.
Идея о Transform появилась, потому что мне надо в уме держать какие в каких именно координатах я возвращаю объекты (например в рендерере мне явным образом пришлось хранить плоскости в координатах мира и в координатах камеры)

2024-03-26 11:15 UTC, DimaTrushin requested changes
У тебя строится очень много временных контейнеров. Надо переработать эту парадигму глобально.
Еще если строишь новые контейнеры, то не называй методы get_something, лучше называй make_something или create_something. Тогда у пользователя метода не будет иллюзий, что они пользуются дешовым методом предоставляющим доступ к данным.

2024-03-26 11:15 UTC, DimaTrushin commented on CMakeLists.txt
> +    message(FATAL_ERROR "This project is g++ only (for now maybe)")
Некрасиво поступаешь. У тебя по сути ничего не используется от gnu компилятора кроме флагов. Мог бы сделать поддержку других компиляторов спрятав пот эту проверку все флаги для gnu.

2024-03-26 11:15 UTC, DimaTrushin commented on src/geometry.h
> +using CordType = double;
Слово Coordinate пишется с двумя "o", такое написание сбивает с толку и не дает понять, что имеется в виду.

2024-03-26 11:15 UTC, DimaTrushin commented on src/geometry.h
> +using RGBColor = Point;  // Move this to appropriate place
Странно, что цвет это просто вектор. Тем более, что вектор в качестве компонент имеет CoordinateType, что совсем противоречит идее того, что цвета это точки. Меня скорее всего смущает именно название типа для координат матриц. Если бы ты просто сделал using FloatType = double и потом его везде использовал, то это было бы ОК.

2024-03-26 11:15 UTC, DimaTrushin commented on src/geometry.h
> +template <int Rows, int Cols>
У Eigen типы для rows и cols это Eigen::Index.

2024-03-26 11:15 UTC, DimaTrushin commented on src/geometry.h
> +// };
Убери закомментированный код, это все останется жить в истории гита.

2024-03-26 11:15 UTC, DimaTrushin commented on src/main.cpp
> +
Надо будет потом завернить это все в класс Application и написать что-то вроде такого
```cpp
#include "Application.h"
#include "Except.h"

int main() {
  try {
    using Application = renderer::Application;
    Application app;
    app.run();
  } catch(...) {
    except::react();
  }
  return 0;
}
Except.h
namespace except {
void react();
}
Except.cpp
#include "Except.h"

namespace except {
void react() {
  try {
    throw;
  } catch(std::exception& e) {
    // обрабатываешь известные исключения
  } catch(...) {
    // обрабатываешь незивестные исключения
  }
}
}
```

2024-03-26 11:15 UTC, DimaTrushin commented on src/main.cpp
> +    std::cerr << "Triangle is created\n";
Зачем ты используешь std::cerr? Почему не std::cout? Вообще в целом плохая идея использовать stderr, к которому привязан std::cerr.

2024-03-26 11:15 UTC, DimaTrushin commented on src/geometry/sphere.h
> +    Point get_center() const;
Это так и задумано возвращать вектор длины 3 по значению?

2024-03-26 11:15 UTC, DimaTrushin commented on src/geometry/sphere.h
> +    void set_center(Point center);
Это так и задумано принимать вектор длины 3 по значению?

2024-03-26 11:15 UTC, DimaTrushin commented on src/geometry/plane.cpp
> +    Matrix<4, 4> op = operation.inverse().transpose();
можешь написать auto op =  и это отложит вычисление.

2024-03-26 11:15 UTC, DimaTrushin commented on src/geometry/plane.cpp
> +void Plane::transform_inplace(const Matrix<4, 4>& operation) {
Судя по всему версия inplace не обладает преимуществом по сравнению с версией возвращающей новый результат.

2024-03-26 11:15 UTC, DimaTrushin commented on src/geometry/plane.cpp
> +using types::Vector4;
Это плохая тема. Если уж ты внутри каждого класса заводишь свои юзинги для типов, то плохо подтягивать сюда глобальные юзинги, если ты изменишь внутри класса локальные, то у тебя будет рассинхрон тут. Я бы убрал из всех пространств имен подобные юзинги и подтягивал их только в классы. Судя по всему это артефакт предыдущей версии кода.

2024-03-26 11:15 UTC, DimaTrushin commented on src/geometry/line.cpp
> +types::Point Line::get_point() const {
Смени на Line::

2024-03-26 11:15 UTC, DimaTrushin commented on src/geometry/line.cpp
> +types::Vector3 Line::get_direction() const {
Смени на Line::

2024-03-26 11:15 UTC, DimaTrushin commented on src/geometry/line.h
> +    using Matrix = types::Matrix<Rows, Cols>;
Ты вроде нигде не пользуешься матрицами тут в классе. Или это для единообразия специально?

2024-03-26 11:15 UTC, DimaTrushin commented on src/object.h
> +    static Object create_triangle(Point p1, Point p2, Point p3);
А не слишком ли накладно передавать 9 даблов?

2024-03-26 11:15 UTC, DimaTrushin commented on src/object.cpp
> +std::vector<Point> Object::get_vertices() const {
А не лучше ли вернуть прокси класс, который эмулирует контейнер вершин и итераторы на нем. И при разыменовывании итератора возвращает не исходную точку, а сдвинутую на position_? Так у тебя не будет конструироваться потенциально большая копия контейнера (а объекты могут состоять из большого количества примитивов).

2024-03-26 11:15 UTC, DimaTrushin commented on src/object.cpp
> +    std::for_each(result.begin(), result.end(), [this](Point& point) { point += this->position_; });
не надо использовать this, можно просто написать point += position_;

2024-03-26 11:15 UTC, DimaTrushin commented on src/object.cpp
> +PrimitivesSet Object::get_primitives() const {
Это потенциально дорого строить новые контейнеры и возвращать из by value. Рекомендуется заменить глагол get на глагол create или make, чтобы пользователь метода хотя бы знал, что он тут платит большую цену за вызов метода. Кроме того, на сколько часто этот метод будет применяться? Если разово, то это не страшно, если же регулярно в циклах, то стоит подумать о каком-то другом методе например через симуляцию контейнера с помощью прокси объекта.

2024-03-26 11:15 UTC, DimaTrushin commented on src/object.h
> +    Object(Point position, const PrimitivesSet& primitives);
Добавь конструктор с сигнатурой
```cpp
Object(Point position, PrimitiveSet&& primitives);
```
чтобы можно было украть внутренности.

2024-03-26 11:15 UTC, DimaTrushin commented on src/object.cpp
> +    return Object(Point(0, 0, 0), ps);
Я бы ожидал тут
```cpp
Object (Point::Origin, std::move(ps));
```
Во-первых, не используется магическая константа. Во-вторых, не копируется зазря множество примитивов, а оно мувается внутрь объекта. Для этого, правда, придется добавить соответствующий конструктор.

2024-03-26 11:15 UTC, DimaTrushin commented on src/primitive.h
> +class PrimitivesSet {
Плохое название класса. Дело в том, что слово set имеет значение конкретной структуры данных. И когда ты пишешь set люди могут ожидать определенную сложность. Потому плохо так называть контейнер содержащий по сути несколько векторов.

2024-03-26 11:15 UTC, DimaTrushin commented on src/primitive.h
> +    // I want to rename this, but I can't understand how for now
Можешь назвать Defines и все. На самом деле ты можешь везде унаследоваться от этого класса. И это другой способ зафиксировать зависимости от типов вместо глобального неймспейса.

2024-03-26 11:15 UTC, DimaTrushin commented on src/primitive.h
> +// This maybe be preferable, because it not limits result to contain the same primitives and doesn't
it does not limit

2024-03-26 11:15 UTC, DimaTrushin commented on src/primitive.h
> +// create useless temporary vector but both solutions seems to be terrible performance wise
А в чем проблема производительности?

2024-03-26 11:15 UTC, DimaTrushin commented on src/primitive.h
> +    using RGBColor = PrimitiveBase::RGBColor;
А почему тут ты не унаследовал эти дефайны?

2024-03-26 11:15 UTC, DimaTrushin commented on src/primitive.h
> +    void push(T value);
Есть пара советов.
1) Обрати внимание как выглядит сигнатура метода push_back например в контейнере std::vector. Он принимает либо const T& либо T&&. Это связано с тем, что класс T может быть дорогим для мува.
2) Если класс T может быть дорогим для построения, копирования или мува, то имеет смысл еще добавить emplace метод, который строит объект заданного типа. Посмотри на сигнатуру метода emplace в std::any
https://en.cppreference.com/w/cpp/utility/any/emplace

2024-03-26 11:15 UTC, DimaTrushin commented on src/primitive.h
> +    // Change vector here to iterable
Да, это ровно та идея с прокси контейнером, что я писал.

2024-03-26 11:15 UTC, DimaTrushin commented on src/primitive.h
> +        result.insert(result.end(), temp.begin(), temp.end());
тут еще и нет reserve

2024-03-26 11:15 UTC, DimaTrushin commented on src/primitive.h
> +template <primitive::IsPrimitive... Primitives>
Я в целом не рекомендую писать определения шаблонов вне класса. Потому что обрати внимание на количество лишнего кода, который приходится писать. В итоге у тебя отношение кода к шуму очень низкое и код менее читаемый. Шаблоны удобнее определять при объвлении и некоторые вещи без этого просто не сделаешь. 

Если уж ты хочешь определять вне класса, то можно выделить один дополнительный хедер primitive_impl.h и включить его в конце этого файла, а все имплементации убрать туда.

Не уверен, что хорошо получилось, что этот код еще и перемешивается у тебя тут с другими классами. Выделение вспомогательного хедера это немного исправит.

2024-03-26 11:15 UTC, DimaTrushin commented on src/primitive.h
> +    std::get<std::vector<T>>(data_).push_back(std::forward<T>(value));
Я бы ожидал тут std::move. Но судя по всему forward в этом случае тоже работает как надо.

2024-03-26 11:15 UTC, DimaTrushin commented on src/primitive.h
> +        [func = std::forward<decltype(func)>(func)](auto&... vectors) {
Тут можно вместо decltype(func) использовать F, будет короче. decltype используется в случае если вместо F у тебя auto.

2024-03-26 11:15 UTC, DimaTrushin commented on src/primitive.h
> +            auto temp = [func = std::forward<decltype(func)>(func)](auto& primitives_vector) {
temp плохое название.

2024-03-26 11:15 UTC, DimaTrushin commented on src/rasterizer.h
> +    using ProjectedPoint = Vector2;
Плохое имя типа. Дело в том, что projectedPoint это скорее название для переменной, а не для типа. Какая разница из каких соображений у тебя взялся вектор длины 2? Это как вместо size_t использовать amout_of_vertices и amount_of_triangles. Какая разница? и там и там у тебя все в штуках мереется. Так же и тут, не нужно вводить в названии типа, что это спроектированная точка. Это больше для имени переменной.

2024-03-26 11:15 UTC, DimaTrushin commented on src/rasterizer.h
> +    using Vertices = std::array<Point, N>;
Почему это не глобальный шаблон? И еще у тебя эта штука имеет тяжелую локальную часть. С этим надо быть аккуратным.

2024-03-26 11:15 UTC, DimaTrushin commented on src/rasterizer.h
> +    // don't know is it worth to create another struct here, because types in it says all
Проблема в том, что у тебя типы слишком говорливые. Они говорят за переменные. То есть у тебя все равно в коде будет first и second, которые ни о чем не говорят. По хорошему у тебя типы не то что надо говорят. Их надо изменить до нормальных имен и уже поля структуры будут говорить своими именами, что же это такое.

2024-03-26 11:15 UTC, DimaTrushin commented on src/rasterizer.h
> +            if (dist < BORDER) {
1) 4 вложенных scope. Даже в ядре Linux запрещено больше 3.
2) почему BORDER написано в стиле CAPS_ONLY? Не используй такой стиль ни для чего кроме макросов. Если нужна константа, используй constexpr выражения и имена вида k_border или kBorder в зависимости от твоего стиля.

2024-03-26 11:15 UTC, DimaTrushin commented on src/rasterizer.h
> +    // This is not efficient for thin triangles, so maybe add another implementation for such
Что это значит в точности?

2024-03-26 11:15 UTC, DimaTrushin commented on src/rasterizer.h
> +                            auto pos = this->to_pixel_position(point);
не используй this

2024-03-26 11:15 UTC, DimaTrushin commented on src/rasterizer.h
> +        ProjectedPoint point = vertices[i].template block<2, 1>(0, 0);
В современных плюсах тут не надо писать template. Оно и так должно сработать.

2024-03-26 11:15 UTC, DimaTrushin commented on src/rasterizer.h
> +template <>
Этот код можно спрятать в cpp файл. Дело в том, что тут ты определяешь функцию и она будет добавлена в бинарник. Это одна из тех ситуаций, где ты можешь явно инстанциировать все версии шаблона (потому что у тебя конечное число вариантов) и сделать эту инстанциацию внутри cpp файла.

2024-03-26 11:15 UTC, DimaTrushin commented on src/renderer.h
> +struct Camera {
Не стоит камеру и рендерер в одном хедере определять. Все кто захотят знать камеру внезапно должны будут узнать и про рендерер.

2024-03-26 11:15 UTC, DimaTrushin commented on src/screen.h
> +    std::vector<std::vector<CordType>> depth_buffer_;
Никогда НЕ используй вектор векторов. Ты можешь использовать Eigen::array или Eigen::Matrix для двумерного массива. Ну либо создай свой контейнер, который внутри содержит один единый std::vector и предоставляет тебе интерфейс двумерногно массива.

2024-03-26 11:15 UTC, DimaTrushin commented on src/screen.h
> +    Dimensions dims_;
Выглядит так, что эта информация уже содержится в буфферах.

2024-03-26 11:15 UTC, DimaTrushin commented on src/screen.h
> +    const std::vector<std::vector<RGBColor>>& get_frame_buffer() const;
Ты столько ввел псевдонимов для коротких названий типов, что странно, что ты не ввел псевдоним для сложного громоздского типа как вектор векторов. Но лучше использовать нормальный буффер.

2024-03-26 11:15 UTC, DimaTrushin commented on src/renderer.cpp
> +            // If object is outside view frustum it can be fully skipped
Почему тогда функция не называется is_outside_view_frustum?

2024-03-26 11:15 UTC, DimaTrushin commented on src/world.h
> +    void push_object(const Object& obj);
добавсь еще push_object(Object&&) для того, чтобы его можно было украсть. а то ты тут все время будешь делать лишнюю копию.

2024-04-20 19:06 UTC, vladl2802 commented on src/object.cpp
> +    return Object(Point(0, 0, 0), ps);
Я не уверен куда лучше засунуть Origin... Сейчас использую Point::Zero(), но выглядит все равно не очень. Возможно статик константа внутри объекта будет лучше.

2024-04-20 19:09 UTC, vladl2802 commented on src/object.h
> +    static Object create_triangle(Point p1, Point p2, Point p3);
Сейчас все еще страшнее, потому что у вершины появился цвет и потому что квадрат и куб требуют более сложного создания. Я не совсем понимаю, как это можно упростить.. Как будто просто передавать и не страшно. Но использовать такое не удобно точно. Возможно билдер или че-нить такое будет удобнее.

2024-04-20 19:17 UTC, vladl2802 commented on src/primitive.h
> +// create useless temporary vector but both solutions seems to be terrible performance wise
Ну получается я сую один примитив внутрь PrimitivesList и начинаю его делить, удаляя и добавляя примитивы. 
Во-первых, у меня PrimitivesList не поддерживает удаление (это я планирую исправить, но врядли успею до 26). 
Во-вторых, жирно как-то создавать тупл векторов только для того, чтобы один треугольник на два разрезать.
Я хочу переписать вообще всё пересечение по аналогии с Rasterizer, где один класс (видимо Intersector) будет уметь пересекать целый PrimitivesList, а не выделять каждый примитив и пересекать его отдельно. Там можно будет и оптимизировать по аллокациям, и добавить возможность пересечению примитива T возвращать не только примитивы T (Например когда пересечение треугольника плоскостью оказывается настолько маленьким, что по сути это отрезок (имеет площадь что-то вроде 1e-15). У меня в этом случае алгоритм растеризации ломается в некотором смысле.)

2024-04-20 19:20 UTC, vladl2802 commented on src/primitive.h
> +template <primitive::IsPrimitive... Primitives>
Внутри класса тогда тяжело становится читать все его методы.. Кажется если переписать на trailing return type (типа вместо T f(...) писать auto f(...) -> T), то тогда мусора станет меньше.
Вообще, я хочу разнести этот файл на несколько, тогда перемешивания будет меньше, но у меня все руки не дойдут.

2024-04-20 19:24 UTC, vladl2802 commented on src/rasterizer.h
> +    using ProjectedPoint = Vector2;
Ну вообще идея была в том, что есть Point и он в 3D, а тут мы спроецировали и получился Point2D, но чтобы обозначить, что получилось именно при проекции, я решил добавить слово Projected. Ну и потому что название Point2D мне не нравится.. пока что оставил Vector2

2024-04-20 19:28 UTC, vladl2802 commented on src/rasterizer.h
> +    // This is not efficient for thin triangles, so maybe add another implementation for such
Вообще я этот коммент скорее для себя оставлял. Вообще я просто итерируюсь по прямоугольнику c 
![Screenshot](https://github.com/vladl2802/3d-renderer/assets/71648037/adafeafd-df0f-4004-8c06-7dad76442125)

2024-04-20 19:32 UTC, vladl2802 commented on src/rasterizer.h
> +        ProjectedPoint point = vertices[i].template block<2, 1>(0, 0);
Это кажется не правда, я так и не смог скомпилить без этого. Но не думаю, что это что-то критичное в любом случае..

2024-04-20 19:35 UTC, vladl2802 commented on src/renderer.h
> +struct Camera {
Апдейт: на самом деле фокусная точка у меня не всегда в центре и на фиксированном расстоянии. left и right например отвечают за границы прямоугольника экрана. Аналогично top и bottom. near - отвечает за расстояние до плоскость экрана от фокусной точки.

2024-05-20 22:02 UTC, merged